# Gradle properties for jauml 26.1.2
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=jauml
group=tn.naizo.jauml
mod_name=Jauml
mod_author=NAIZO
version=2.1.1
minecraft_version=26.1.2
java_version=25
fabric_version=0.149.1+26.1.2
fabric_loader_version=0.19.3
license=MIT
description=Just Another Utility Minecraft Lib
neoforge_version=26.1.2.33-beta
neoforge_loader_version_range=[11,)
neoforge_version_range=[26.1.2,)
minecraft_version_range=[26.1.2,27)
credits=NAIZO
neo_form_version=26.1.2-1
