# Gradle properties for jauml 26.3
# Every field you add must be added to build-logic/src/main/groovy/multiloader-common.gradle expandProps map.

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

group=tn.naizo.jauml
mod_id=jauml
mod_name=Jauml
mod_author=NAIZO
version=2.3.1
minecraft_version=26.3
java_version=25
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5
license=Apache-2.0
description=Just Another Utility Minecraft Lib
neoforge_version=26.3.0.38-beta
neoforge_loader_version_range=[12,)
neoforge_version_range=[26.3,)
minecraft_version_range=[26.3,27)
credits=NAIZO
neo_form_version=26.3-1
