# Gradle properties for jauml 26.2
# Every field you add must be added to build-logic/src/main/groovy/multiloader-common.gradle expandProps map.

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

group=tn.naizo.jauml
mod_id=jauml
mod_name=Jauml
mod_author=NAIZO
version=2.1.1
minecraft_version=26.2
java_version=25
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3
license=MIT
description=Just Another Utility Minecraft Lib
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[11,)
neoforge_version_range=[26.2,)
minecraft_version_range=[26.2,27)
credits=NAIZO
neo_form_version=26.2-1
